workspace:
  base: /var/www/owncloud
  path: apps/guests

pipeline:
  install-core:
    image: owncloudci/core
    version: ${OC_VERSION}
    pull: true
    db_type: ${DB_TYPE}
    db_name: ${DB_NAME}
    db_host: ${DB_TYPE}
    db_username: autotest
    db_password: owncloud
    when:
      matrix:
        NEED_CORE: true

  install-testrunner:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - git clone -b master --depth=1 https://github.com/owncloud/core.git /var/www/owncloud/testrunner
      - cp -r /var/www/owncloud/apps/guests /var/www/owncloud/testrunner/apps/
      - cd /var/www/owncloud/testrunner
      - make install-composer-deps
      - make vendor-bin-deps
    when:
      matrix:
        USE_RELEASE_TARBALL: true

  install-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/
      - php occ a:l
      - php occ a:e guests
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=owncloud
      - php occ log:manage --level 2
    when:
      matrix:
        NEED_INSTALL_APP: true

  install-user-management-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - git clone https://github.com/owncloud/user_management.git /var/www/owncloud/apps/user_management
      - cd /var/www/owncloud/
      - php occ a:l
      - php occ a:e user_management
      - php occ a:l
    when:
      matrix:
        NEED_USER_MANAGEMENT_APP: true

  prepare-objectstore:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/apps
      - git clone https://github.com/owncloud/files_primary_s3.git
      - cd files_primary_s3
      - composer install
      - cp tests/drone/scality.config.php /var/www/owncloud/config
      - cd /var/www/owncloud
      - php occ a:l
      - php occ a:e files_primary_s3
      - php occ a:l
      - php occ s3:create-bucket owncloud --accept-warning
    when:
      matrix:
        TEST_OBJECTSTORAGE: true

  fix-permissions:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - chown www-data /var/www/owncloud -R
      - if [ "${USE_RELEASE_TARBALL}" = "true" ];
        then
        chmod 777 /var/www/owncloud/testrunner/tests/acceptance/filesForUpload -R;
        chmod +x /var/www/owncloud/testrunner/tests/acceptance/run.sh;
        else
        chmod 777 /var/www/owncloud/tests/acceptance/filesForUpload -R;
        chmod +x /var/www/owncloud/tests/acceptance/run.sh;
        fi
    when:
      matrix:
        FIX_PERMISSIONS: true

  owncloud-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
      - tail -f /var/www/owncloud/data/owncloud.log
    when:
      matrix:
        NEED_SERVER: true

  test-javascript:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-js
    when:
      matrix:
        TEST_SUITE: javascript

  owncloud-coding-standard:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-php-codecheck
      - make test-php-style
    when:
      matrix:
        TEST_SUITE: owncloud-coding-standard

  phpunit-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - COVERAGE=${COVERAGE}
    commands:
      - if [ -z "${COVERAGE}" ]; then make test-php-unit; fi
      - if [ "${COVERAGE}" = "true" ]; then make test-php-unit-dbg; fi
    when:
      matrix:
        TEST_SUITE: phpunit

  api-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - TEST_SERVER_URL=http://owncloud
      - MAILHOG_HOST=email
      - BEHAT_SUITE=${BEHAT_SUITE}
    commands:
      - if [ "${USE_RELEASE_TARBALL}" = "true" ]; then cd /var/www/owncloud/testrunner/apps/guests; fi
      - make test-acceptance-api
    when:
      matrix:
        TEST_SUITE: api-acceptance

  webui-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - BROWSER=chrome
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_SERVER_URL=http://owncloud
      - PLATFORM=Linux
      - BEHAT_SUITE=${BEHAT_SUITE}
      - MAILHOG_HOST=email
    commands:
      - if [ "${USE_RELEASE_TARBALL}" = "true" ]; then cd /var/www/owncloud/testrunner/apps/guests; fi
      - make test-acceptance-webui
    when:
      matrix:
        TEST_SUITE: webui-acceptance

  codecov:
    image: plugins/codecov:2
    secrets: [codecov_token]
    pull: true
    files:
      - '*.xml'
    paths:
      - tests/output
    when:
      matrix:
        COVERAGE: true

  notify:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: builds
    when:
      status: [ failure, changed ]
      event: [ push, tag ]

services:
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_USER=autotest
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mysql

  pgsql:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=autotest
      - POSTGRES_PASSWORD=owncloud
      - POSTGRES_DB=${DB_NAME}
    when:
      matrix:
        DB_TYPE: pgsql

  oci:
    image: deepdiver/docker-oracle-xe-11g
    environment:
      - ORACLE_USER=system
      - ORACLE_PASSWORD=oracle
      - ORACLE_DB=${DB_NAME}
    when:
      matrix:
        DB_TYPE: oci

  owncloud:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
     - APACHE_WEBROOT=/var/www/owncloud/
    command: [ "/usr/local/bin/apachectl", "-e", "debug", "-D", "FOREGROUND" ]
    when:
      matrix:
        NEED_SERVER: true

  selenium:
    image: selenium/standalone-chrome-debug:3.141.59-oxygen
    pull: true
    when:
      matrix:
        TEST_SUITE: webui-acceptance

  email:
    image: mailhog/mailhog
    pull: true
    when:
      matrix:
        USE_EMAIL: true

  scality:
    image: owncloudci/scality-s3server
    pull: true
    environment:
      - HOST_NAME=scality
    when:
      matrix:
        TEST_OBJECTSTORAGE: true

matrix:
  include:
    # Javascript
    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: javascript
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true

    # owncloud-coding-standard
    - PHP_VERSION: 7.2
      TEST_SUITE: owncloud-coding-standard
      OC_VERSION: daily-master-qa
      NEED_CORE: true

    - PHP_VERSION: 7.0
      TEST_SUITE: owncloud-coding-standard
      OC_VERSION: daily-master-qa
      NEED_CORE: true

    # Unit Tests against core master
    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      COVERAGE: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      COVERAGE: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: pgsql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      COVERAGE: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: oci
      DB_NAME: XE
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      COVERAGE: true

    - PHP_VERSION: 7.0
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true

    # API Acceptance Tests with core master
    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiGuests
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      FIX_PERMISSIONS: true
      USE_EMAIL: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiGuests
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      FIX_PERMISSIONS: true
      USE_EMAIL: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiGuests
      DB_TYPE: pgsql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      FIX_PERMISSIONS: true
      USE_EMAIL: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiGuests
      DB_TYPE: oci
      DB_NAME: XE
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      FIX_PERMISSIONS: true
      USE_EMAIL: true

    # webUI Acceptance Tests with core master
    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: webui-acceptance
      BEHAT_SUITE: webUIGuests
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      FIX_PERMISSIONS: true
      USE_EMAIL: true
      NEED_USER_MANAGEMENT_APP: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: webui-acceptance
      BEHAT_SUITE: webUIGuests
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      FIX_PERMISSIONS: true
      USE_EMAIL: true
      NEED_USER_MANAGEMENT_APP: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: webui-acceptance
      BEHAT_SUITE: webUIGuests
      DB_TYPE: pgsql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      FIX_PERMISSIONS: true
      USE_EMAIL: true
      NEED_USER_MANAGEMENT_APP: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: webui-acceptance
      BEHAT_SUITE: webUIGuests
      DB_TYPE: oci
      DB_NAME: XE
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      FIX_PERMISSIONS: true
      USE_EMAIL: true
      NEED_USER_MANAGEMENT_APP: true

# TODO: needs to be uncommented once 10.3 is available
#      # Release Tarball
#    - PHP_VERSION: 7.1
#      OC_VERSION: 10.3.0
#      TEST_SUITE: api-acceptance
#      BEHAT_SUITE: apiGuests
#      DB_TYPE: mysql
#      DB_NAME: owncloud
#      NEED_SERVER: true
#      NEED_INSTALL_APP: true
#      USE_EMAIL: true
#      NEED_CORE: true
#      USE_RELEASE_TARBALL: true
#      FIX_PERMISSIONS: true
#
#    - PHP_VERSION: 7.1
#      OC_VERSION: 10.3.0
#      TEST_SUITE: webui-acceptance
#      BEHAT_SUITE: webUIGuests
#      DB_TYPE: mysql
#      DB_NAME: owncloud
#      NEED_SERVER: true
#      NEED_INSTALL_APP: true
#      USE_EMAIL: true
#      NEED_CORE: true
#      USE_RELEASE_TARBALL: true
#      FIX_PERMISSIONS: true
