workspace:
  base: /var/www/owncloud
  path: apps/guests

branches: [master, release*, release/*]

pipeline:
  install-server:
    image: owncloudci/core
    pull: true
    version: ${OC_VERSION}

  install-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/apps/guests
      - make
      - cd /var/www/owncloud/
      - php occ a:l
      - php occ a:e guests
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=owncloud
      - php occ log:manage --level 0
    when:
      matrix:
        TEST_SUITE: php

  prepare-objectstore:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/apps
      - git clone https://github.com/owncloud/files_primary_s3.git
      - cd files_primary_s3
      - composer install
      - cp tests/drone/scality.config.php /var/www/owncloud/config
      - cd /var/www/owncloud
      - php occ a:l
      - php occ a:e files_primary_s3
      - php occ a:l
      - php occ s3:create-bucket owncloud --accept-warning
    when:
      matrix:
        TEST_OBJECTSTORAGE: true

  test-javascript:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-js
    when:
      matrix:
        TEST_SUITE: javascript

  code-compliance-check:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-php-lint
      - make test-php-codecheck
      - make test-php-style
    when:
      matrix:
        TEST_SUITE: php

  api-acceptance:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - MAILHOG_HOST=mailhog
    commands:
      - make test-acceptance
    when:
      matrix:
        TEST_SUITE: php

  print-log:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cat /var/www/owncloud/data/owncloud.log
    when:
      status:  [ failure ]

  notify:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: builds
    when:
      status: [ failure, changed ]
      event: [ push, tag ]

services:
  mailhog:
    image: mailhog/mailhog
    pull: true
    when:
      matrix:
        TEST_SUITE: php

  scality:
    image: owncloudci/scality-s3server
    pull: true
    environment:
      - HOST_NAME=scality
    when:
      matrix:
        TEST_OBJECTSTORAGE: true

matrix:
  include:
    # Javascript
    - TEST_SUITE: javascript
      OC_VERSION: daily-master-qa
      PHP_VERSION: 7.1

    - TEST_SUITE: javascript
      OC_VERSION: daily-stable10-qa
      PHP_VERSION: 7.1

    # PHP Tests
    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: php

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: php

    - PHP_VERSION: 5.6
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: php

    - PHP_VERSION: 7.0
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: php

    - PHP_VERSION: 7.1
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: php

    - PHP_VERSION: 7.2
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: php

      # Test on Objectstore
    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: php
      TEST_OBJECTSTORAGE: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: php
      TEST_OBJECTSTORAGE: true